[variables]
NIXPACKS_PYTHON_PACKAGE_MANAGER = "requirements"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.sqlite",
  "python311Packages.lxml",
  "python311Packages.libxml2",
  "python311Packages.libxslt",
  "python311Packages.openssl",
  "python311Packages.gunicorn"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 120 main:app"

